header:
  license:
    spdx-id: GPL-3.0-or-later
    copyright-owner: SUTD

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'

  comment: on-failure

# If you don't want to check dependencies' license compatibility, remove the following part
dependency:
  files:
    - pom.xml           # If this is a maven project.
    - Cargo.toml        # If this is a rust project.
    - package.json      # If this is a npm project.
    - go.mod            # If this is a Go project.
    - Gemfile.lock      # If this is a Ruby project (Bundler). Ensure Gemfile.lock is committed.